# Generated by Django 3.0.5 on 2020-05-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0003_auto_20200519_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_type', models.CharField(choices=[('solid', 'solid'), ('liquid', 'liquid')], max_length=50, null=True)),
                ('medicine_open_stock', models.FloatField(null=True)),
                ('medicine_stock_available', models.FloatField(null=True)),
                ('medicine_stock_type', models.CharField(choices=[('kg', 'kg'), ('ltr', 'ltr'), ('tonnes', 'tonnes')], max_length=50, null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.company')),
            ],
        ),
    ]
