# Generated by Django 3.0.5 on 2020-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_company_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_mrp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
