# Generated by Django 3.0.5 on 2020-06-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200602_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
