# Generated by Django 3.0.5 on 2020-06-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20200602_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bill_no',
        ),
    ]
