# Generated by Django 3.0.5 on 2020-06-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
