# Generated by Django 3.0.5 on 2020-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_billed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
