# Generated by Django 3.0.5 on 2020-06-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_complete',
            field=models.BooleanField(default=False),
        ),
    ]
